name: Upload to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload root HTML files
        run: |
          for file in *.html; do
            aws s3 cp "$file" "s3://${{ secrets.S3_BUCKET }}/$(basename "${file%.html}")" \
              --content-type text/html \
              --acl public-read
          done

      - name: Upload projects HTML files
        run: |
          for file in projects/*.html; do
            aws s3 cp "$file" "s3://${{ secrets.S3_BUCKET }}/projects/$(basename "${file%.html}")" \
              --content-type text/html \
              --acl public-read
          done

      - name: Upload assets directory
        run: |
          aws s3 cp assets/ "s3://${{ secrets.S3_BUCKET }}/assets/" \
            --recursive \
            --acl public-read